[build]
  base = "ticaret-deneme/frontend"
  command = "npm run build"
  publish = "dist"
  functions = "ticaret-deneme/frontend/netlify/functions"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 